services:

  api:
    build:
      context: ./api_crimes_san_francisco
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./api_crimes_san_francisco/crimesSF-api/model-pkg/model.pkl:/opt/crimessf-api/model-pkg/model.pkl
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - MOCK_MODE=false
      - API_URL=http://api:8001
    volumes:
      - ./api_crimes_san_francisco/crimesSF-api/model-pkg/model.pkl:/opt/MLFLOW_BACKUP/SF-Crimes-MultiModel-FE/models/Xgboost/artifacts/model.pkl
      - ./MLFLOW_BACKUP/SF-Crimes-MultiModel-FE/models/Xgboost/artifacts/classes.json:/opt/MLFLOW_BACKUP/SF-Crimes-MultiModel-FE/models/Xgboost/artifacts/classes.json
    depends_on:
      - api
    restart: unless-stopped
