package_name: sfcrime-model

train_data_file: train.csv
test_data_file: test.csv

pipeline_save_file: sfcrime-model-output

target: Category

drop_cols:
  - Descript
  - Resolution

test_size: 0.2
random_state: 42

n_estimators: 100
max_depth: 4
learning_rate: 0.1
subsample: 0.8
colsample_bytree: 0.8
num_classes: 39

mlflow_tracking_uri: "file:./mlruns"
mlflow_experiment_name: "sf-crime-classification"
